/** getting all pokemons */ 

export const GET_ALL_POKEMONS_REQUEST = "GET_ALL_POKEMONS_REQUEST";
export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";
export const GET_ALL_POKEMONS_FAILURE = "GET_ALL_POKEMONS_FAILURE";