/** getting all pokemons */ 

export const GET_ALL_POKEMONS_REQUEST = "GET_ALL_POKEMONS_REQUEST";
export const GET_ALL_POKEMONS_SUCCESS = "GET_ALL_POKEMONS_SUCCESS";
export const GET_ALL_POKEMONS_FAILURE = "GET_ALL_POKEMONS_FAILURE";

/** getting Pokemons profile */ 

export const GET_POKEMON_PROFILE_REQUEST= "GET_POKEMON_PROFILE_REQUEST";
export const GET_POKEMON_PROFILE_SUCCESS= "GET_POKEMON_PROFILE_SUCCESS";
export const GET_POKEMON_PROFILE_FAILURE= "GET_POKEMON_PROFILE_FAILURE";

/** getting Pokemons Description */ 

export const GET_POKEMON_DESCRIPTION_REQUEST= "GET_POKEMON_DESCRIPTION_REQUEST";
export const GET_POKEMON_DESCRIPTION_SUCCESS= "GET_POKEMON_DESCRIPTION_SUCCESS";
export const GET_POKEMON_DESCRIPTION_FAILURE= "GET_POKEMON_DESCRIPTION_FAILURE";